tool_descriptions = {
    "dashboard_search_replace": "Applying changes to dashboard HTML",
    "apply_html_patch": "Applying HTML patch to dashboard",
    "start_html_generation": "Starting dashboard HTML generation",
    "save_query": "Saving query for later use",
    "get_database_schema": "Fetching database schema",
    "get_chart_styling": "Getting chart styling examples",
    "get_existing_html": "Loading existing dashboard HTML",
    "saved_query_schema": "Getting saved query schemas",
    "get_user_style_guidelines": "Getting user style guidelines",
    "execute_sql_query": "Executing SQL query",
    "execute_mongo_query": "Executing MongoDB query",
    "execute_duckdb_query": "Executing DuckDB query",
    "get_filter_options": "Getting filter options for dashboard column",
    "define_dashboard_filters": "Creating dashboard filters",
    "update_dashboard_filter": "Updating dashboard filter",
    "remove_dashboard_filter": "Removing dashboard filter",
    "get_dashboard_filter_config": "Loading filter configuration",
    "execute_skill_api": "Executing external API request",
    "search_enabled_skills": "Searching for available integrations",
    "get_skill_definition": "Loading skill API documentation",
    "update_custom_skill": "Updating skill instructions",
    "add_learning": "Saving learning to knowledge base",
    "update_learning": "Updating learning in knowledge base",
    "search_learnings": "Searching knowledge base for past learnings",
    "get_learning": "Loading learning from knowledge base",
    "remove_learning": "Removing learning from knowledge base",
    "add_memory": "Saving to workspace memory",
    "search_memory": "Searching workspace memory",
    "remove_memory": "Removing from workspace memory",
    "search_instructions": "Searching instructions",
    "create_repo_skill": "Creating custom repository analysis skill",
    "read_local_repo_file": "Reading file from local repository",
    "search_local_repo_files": "Searching files in local repository",
    "grep_local_repo": "Searching file contents in local repository",
    "list_local_repo_directory": "Listing directory in local repository",
    "get_local_repo_skill": "Loading local repository skill",
}


def get_user_friendly_tool_description(tool_name: str) -> str:
    return tool_descriptions.get(tool_name, tool_name)
