"""add_source_url_to_files

Revision ID: 67c716bfaa02
Revises: f8d3e7a1b2c4
Create Date: 2025-11-10 23:07:04.535566

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '67c716bfaa02'
down_revision = 'f8d3e7a1b2c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('source_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'source_url')
    # ### end Alembic commands ###

