"""add schema cache to connections

Revision ID: add_schema_cache_001
Revises: 9b93beb8636d
Create Date: 2025-08-31 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_schema_cache_001'
down_revision = '9b93beb8636d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('schema_cache', sa.Text(), nullable=True))
    op.add_column('connections', sa.Column('schema_updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'schema_updated_at')
    op.drop_column('connections', 'schema_cache')
    # ### end Alembic commands ###